ALTER TABLE "asset_computer_details"
ADD COLUMN IF NOT EXISTS "mobile_model" TEXT,
ADD COLUMN IF NOT EXISTS "imei" TEXT,
ADD COLUMN IF NOT EXISTS "modem_firmware_version" TEXT,
ADD COLUMN IF NOT EXISTS "udid" TEXT,
ADD COLUMN IF NOT EXISTS "is_personal_asset" TEXT,
ADD COLUMN IF NOT EXISTS "mobile_serial_number" TEXT,
ADD COLUMN IF NOT EXISTS "available_capacity" TEXT,
ADD COLUMN IF NOT EXISTS "available_capacity_unit" TEXT,
ADD COLUMN IF NOT EXISTS "total_capacity" TEXT,
ADD COLUMN IF NOT EXISTS "total_capacity_unit" TEXT,
ADD COLUMN IF NOT EXISTS "os_type" TEXT,
ADD COLUMN IF NOT EXISTS "mobile_build_version" TEXT,
ADD COLUMN IF NOT EXISTS "mobile_os_version" TEXT,
ADD COLUMN IF NOT EXISTS "hardware_encryption" TEXT,
ADD COLUMN IF NOT EXISTS "passcode_compliant" TEXT,
ADD COLUMN IF NOT EXISTS "passcode_compliant_profile" TEXT,
ADD COLUMN IF NOT EXISTS "passcode_present" TEXT,
ADD COLUMN IF NOT EXISTS "allow_adding_game_center_friends" TEXT,
ADD COLUMN IF NOT EXISTS "allow_installing_applications" TEXT,
ADD COLUMN IF NOT EXISTS "allow_in_application_purchase" TEXT,
ADD COLUMN IF NOT EXISTS "allow_use_of_camera" TEXT,
ADD COLUMN IF NOT EXISTS "allow_face_time" TEXT,
ADD COLUMN IF NOT EXISTS "allow_multi_player_gaming" TEXT,
ADD COLUMN IF NOT EXISTS "allow_screen_capture" TEXT,
ADD COLUMN IF NOT EXISTS "allow_automatic_sync_when_roaming" TEXT,
ADD COLUMN IF NOT EXISTS "allow_voice_dialing" TEXT,
ADD COLUMN IF NOT EXISTS "force_encrypted_backups" TEXT,
ADD COLUMN IF NOT EXISTS "accept_cookies" TEXT,
ADD COLUMN IF NOT EXISTS "allow_use_of_itunes_music_store" TEXT,
ADD COLUMN IF NOT EXISTS "allow_use_of_safari" TEXT,
ADD COLUMN IF NOT EXISTS "allow_use_of_youtube" TEXT,
ADD COLUMN IF NOT EXISTS "allow_popups" TEXT,
ADD COLUMN IF NOT EXISTS "enable_auto_fill" TEXT,
ADD COLUMN IF NOT EXISTS "enable_java_script" TEXT,
ADD COLUMN IF NOT EXISTS "allow_explicit_music_and_podcasts" TEXT,
ADD COLUMN IF NOT EXISTS "force_fraud_warning" TEXT,
ADD COLUMN IF NOT EXISTS "activate_data_network" TEXT,
ADD COLUMN IF NOT EXISTS "allow_background_data" TEXT,
ADD COLUMN IF NOT EXISTS "allow_bluetooth" TEXT,
ADD COLUMN IF NOT EXISTS "allow_nfc" TEXT,
ADD COLUMN IF NOT EXISTS "device_admin" TEXT;

CREATE TABLE IF NOT EXISTS "asset_mobile_networks" (
  "id" SERIAL PRIMARY KEY,
  "asset_id" INTEGER NOT NULL REFERENCES "assets"("id") ON DELETE CASCADE,
  "bluetooth_mac" TEXT,
  "carrier_settings_version" TEXT,
  "cellular_technology" TEXT,
  "current_carrier_network" TEXT,
  "current_mcc" TEXT,
  "current_mnc" TEXT,
  "iccid" TEXT,
  "data_roaming_enabled" TEXT,
  "roaming_enabled" TEXT,
  "voice_roaming_enabled" TEXT,
  "phone_number" TEXT,
  "sim_carrier_network" TEXT,
  "subscriber_mcc" TEXT,
  "subscriber_mnc" TEXT,
  "wifi_mac" TEXT,
  "created_on" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_on" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "asset_mobile_certificates" (
  "id" SERIAL PRIMARY KEY,
  "asset_id" INTEGER NOT NULL REFERENCES "assets"("id") ON DELETE CASCADE,
  "name" TEXT,
  "identity" TEXT,
  "created_on" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_on" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "asset_mobile_networks_asset_id_idx" ON "asset_mobile_networks"("asset_id");
CREATE INDEX IF NOT EXISTS "asset_mobile_certificates_asset_id_idx" ON "asset_mobile_certificates"("asset_id");
